### ISSUE TITLE
Support latest clang-tidy 18 version

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [ZedThree/clang-tidy-review#138] opened 2024-11-04 17:32 UTC
Upgrade clang-tidy to `18.1.8`.

---

I've noticed that the current version doesn't handle the check `readability-convert-member-functions-to-static` well; therefore, it might be useful to bump its version.

**Comment by ZedThree** [comment] 2024-11-07 09:32
Duplicate of #134

**Closed by ZedThree** 2024-11-07 09:32 UTC
